services:
  backend:
    container_name: eispunkt-backend
    build:
      context: ../backend
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/eispunkt
      - QUARKUS_DATASOURCE_USERNAME=admin
      - QUARKUS_DATASOURCE_PASSWORD=eispunkt#4040#
    depends_on:
      - postgres
    networks:
      - eispunkt-net
      
